routes/web.php
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {
    /*
    |--------------------------------------------------------------------------
    | CKEditor Images Upload
    |--------------------------------------------------------------------------
    */
    Route::post('/upload_image', function() {
        $CKEditor = Input::get('CKEditor');
        $funcNum = Input::get('CKEditorFuncNum');
        $message = $url = '';
        if (Input::hasFile('upload')) {
            $file = Input::file('upload');
            if ($file->isValid()) {
                $filename = $file->getClientOriginalName();
                $file->move(storage_path().'/images/', $filename);
                $url = public_path() .'/images/' . $filename;
            } else {
                $message = 'An error occured while uploading the file.';
            }
        } else {
            $message = 'No file uploaded.';
        }
        return '<script>window.parent.CKEDITOR.tools.callFunction('.$funcNum.', "'.$url.'", "'.$message.'")</script>';
    });


    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');



    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

    });
    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
        /*
        |--------------------------------------------------------------------------
        | Recipe Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('recipes', 'RecipesController', ['except' => ['show']]);
        Route::get('team/{slug}', 'RecipesController@showBySlug');
        Route::post('recipes/search', [
            'as' => 'recipes.search',
            'uses' => 'RecipesController@search'
            ]);

        /*
        |--------------------------------------------------------------------------
        | Device Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('devices', 'DevicesController', ['except' => ['show']]);
        Route::post('devices/search', [
            'as' => 'devices.search',
            'uses' => 'DevicesController@search'
            ]);



        
        /*
        |--------------------------------------------------------------------------
        | File Manager
        |--------------------------------------------------------------------------
        */ 

        Route::group(['prefix' => 'filemanager','middleware' => 'auth'], function() {    
            Route::get('admin', 'FilemanagerLaravelController@getAdmin');
            Route::get('show', 'FilemanagerLaravelController@getShow');
            Route::post('connectors', 'FilemanagerLaravelController@postConnectors');
        });



        /*
        |--------------------------------------------------------------------------
        | Preparation Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('preparations', 'PreparationsController', ['except' => ['show']]);
        Route::post('preparations/search', [
            'as' => 'preparations.search',
            'uses' => 'PreparationsController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Ingredient Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('ingredients', 'IngredientsController', ['except' => ['show']]);
        Route::post('ingredients/search', [
            'as' => 'ingredients.search',
            'uses' => 'IngredientsController@search'
        ]);


        /*
        |--------------------------------------------------------------------------
        | Category Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('categories', 'CategoriesController', ['except' => ['show']]);
        Route::post('categories/search', [
            'as' => 'categories.search',
            'uses' => 'CategoriesController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Step Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('steps', 'StepsController', ['except' => ['show']]);
        Route::post('steps/search', [
            'as' => 'steps.search',
            'uses' => 'StepsController@search'
        ]);
        /*
        |-------------------------------------------------------------
        | Location Routes
        |-------------------------------------------------------------
        */

        Route::resource('locations', 'LocationsController', ['except' => ['show']]);
        Route::post('locations/search', [
            'as' => 'locations.search',
            'uses' => 'LocationsController@search'
        ]);

        
        
    });
});
Route::get('admin/filemanager/connectors', 'FilemanagerLaravelController@getConnectors');

Route::group(['middleware' => 'cacheable'], function () {
    /*
    |--------------------------------------------------------------------------
    | Welcome Page
    |--------------------------------------------------------------------------
    */

    Route::get('/', 'PagesController@home');

    
    

    /*
    |--------------------------------------------------------------------------
    | Image Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('images', 'ImagesController', ['except' => ['show']]);
    Route::post('images/search', [
        'as' => 'images.search',
        'uses' => 'ImagesController@search'
    ]);

app/Models/Preparation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Preparation extends Model
{
    public $table = "preparations";
    //
    public static $rules = [
        'name' => 'required|min:4',
        'content' => 'max:128',
        'slug' => 'max:30',
        'recipe_id' => 'required'
    ];
    public $fillable = [
        'id',
        'name',
        'slug',
        'content',
        'recipe_id'
        ];

    public function recipe() {
        return $this->belongsTo('App\Models\Recipe');
    }
    public function steps() {
        return $this->hasMany('App\Models\Step');
    }
    public function ingredients() {
        return $this->hasMany('App\Models\Ingredient');
    } 

    public function save(array $options = [])
    {
        if( empty($this->slug) ) {
            $this->setSlugAttribute();
        }
        if( empty($this->content) ) {
            $this->content = $this->name;
        }
        parent::save();
    }
    // Here I want to auto generate slug based on the title
    public function setSlugAttribute(){
        $this->attributes['slug'] = str_slug($this->name , "-");
    }
}

app/Http/Controllers/Api/PreparationsController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\PreparationService;
use App\Http\Requests\PreparationRequest;

class PreparationsController extends Controller
{
    public function __construct(PreparationService $preparationService)
    {
        $this->service = $preparationService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $preparations = $this->service->paginated();
        return response()->json($preparations);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $preparations = $this->service->search($request->search);
        return response()->json($preparations);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\PreparationRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PreparationRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to create preparation'], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $preparation = $this->service->find($id);
        return response()->json($preparation);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\PreparationRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PreparationRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to update preparation'], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return response()->json(['success' => 'preparation was deleted'], 200);
        }

        return response()->json(['error' => 'Unable to delete preparation'], 500);
    }
}

app/Http/Controllers/PreparationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\PreparationService;
use App\Http\Requests\PreparationCreateRequest;
use App\Http\Requests\PreparationUpdateRequest;

class PreparationsController extends Controller
{
    public function __construct(PreparationService $preparationService)
    {
        $this->service = $preparationService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $preparations = $this->service->paginated();
        return view('preparations.index')->with('preparations', $preparations);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $preparations = $this->service->search($request->search);
        return view('preparations.index')->with('preparations', $preparations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('preparations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\PreparationCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PreparationCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('preparations.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('preparations.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the preparation.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $preparation = $this->service->find($id);
        return view('preparations.show')->with('preparation', $preparation);
    }

    /**
     * Show the form for editing the preparation.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $preparation = $this->service->find($id);
        return view('preparations.edit')->with('preparation', $preparation);
    }

    /**
     * Update the preparations in storage.
     *
     * @param  \Illuminate\Http\PreparationUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PreparationUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the preparations from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('preparations.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('preparations.index'))->with('message', 'Failed to delete');
    }
}

resources/views/preparations/create.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Create'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'preparations.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Preparations: Create</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {!! Form::open(['route' => 'preparations.store']) !!}
            <?php 
            $columns = FormMaker::getTableColumns('preparations');
            $recipe_id = @$_GET['recipe'] || '';
            $allRecipes = \App\Models\Recipe::all();
            unset($columns['recipe_id']);
            ?>
            @form_maker_object(null, $columns)
            {!! Form::label('Receta') !!}
            <select id="recipe-selector" class="selectpicker form-control" data-live-search="true" name="recipe_id">
                @foreach ($allRecipes as $recipe)
                    <option data-tokens="{{ $recipe->id }}" value="{{ $recipe->id }}" <?php echo ($recipe_id == $recipe->id)? 'selected':''?> >
                        {{ $recipe->name }}
                    </option>
                @endforeach
            </select>

            {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/preparations/edit.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Edit'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'preparations.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Preparations: Edit</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('preparations.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            {!! Form::model($preparation, ['route' => ['preparations.update', $preparation->id], 'method' => 'patch']) !!}
            <?php 
            $columns = FormMaker::getTableColumns('preparations');
            $allRecipes = \App\Models\Recipe::all();
            unset($columns['recipe_id']);
            ?>
            @form_maker_object($preparation, $columns)
            {!! Form::label('Receta') !!}
            <select id="recipe-selector" class="selectpicker form-control" data-live-search="true" name="recipe_id" >
                @foreach ($allRecipes as $recipe)
                    <option data-tokens="{{ $recipe->id }}" value="{{ $recipe->id }}" <?php echo ($preparation->recipe->id == $recipe->id)? 'selected':''?> >
                        {{ $recipe->name }}
                    </option>
                @endforeach
            </select>



            {!! Form::submit('Actualizar', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>
    <div class="ingredients-wrapper">
            <div class="col-md-12 clearfix">
                <h3 class="pull-left">Ingredientes</h3>
                <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('ingredients.create', array('preparation' => $preparation->id)) !!}"><i class="fa fa-plus" aria-hidden="true"></i>Agregar</a>
            </div>
            <div class="col-md-12">
                @if ($preparation->ingredients->isEmpty())
                    <div class="col-md-12 raw-margin-bottom-24">
                        <div class="well text-center">No se encuentran ingredientes.</div>
                    </div>
                @else
                    <table class="table table-striped">
                        <thead>
                            <th>Name</th>
                            <th>Quantity</th>
                            <th class="text-right">Action</th>
                        </thead>
                        <tbody>
                            @foreach($preparation->ingredients as $ingredient)
                                <tr>
                                    <td>{{ $ingredient->name }}</td>
                                    <td>{{ $ingredient->quantity }} {{ $ingredient->units->name }}</td>
                                    <td class="text-right">
                                        
                                        <a class="btn btn-default btn-xs" href="{{ url('admin/ingredients/'.$ingredient->id.'/edit') }}"><i class="fa fa-pencil" aria-hidden="true"></i>Edit</a>
                                        
                                        
                                        <a class="btn btn-danger btn-xs" href="{{ url('admin/ingredients/'.$ingredient->id.'/remove') }}" onclick="return confirm('Estas seguro de querer eliminar este ingrediente?')">Remove</a>
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
                
            </div>
    </div>
    <div class="steps-wrapper">
            <div class="col-md-12 clearfix">
                <h3 class="pull-left">Pasos</h3>
                <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('steps.create', array('preparation' => $preparation->id)) !!}"><i class="fa fa-plus" aria-hidden="true"></i>Agregar</a>
            </div>
            <div class="col-md-12">
                @if ($preparation->steps->isEmpty())
                    <div class="col-md-12 raw-margin-bottom-24">
                        <div class="well text-center">No se encuentran pasos.</div>
                    </div>
                @else
                    <table class="table table-striped">
                        <thead>
                            <th style="">Name</th>
                            <th style="">Tiempo<br>Cocción</th>
                            <th class="text-right">Action</th>
                        </thead>
                        <tbody>
                            @foreach($preparation->steps as $step)
                                <tr>
                                    <td>{{ $step->content }}</td>
                                    <td>{{ empty($step->duration)? 0:$step->duration }} min</td>
                                    <td class="text-right">
                                        
                                        <a class="btn btn-default btn-xs" href="{{ url('admin/steps/'.$step->id.'/edit') }}"><i class="fa fa-pencil" aria-hidden="true"></i>Edit</a>
                                        
                                        
                                        <a class="btn btn-danger btn-xs" href="{{ url('admin/steps/'.$step->id.'/remove') }}" onclick="return confirm('Estas seguro de querer eliminar este paso?')">Remove</a>
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
                
            </div>
    </div>
@stop

resources/views/preparations/index.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Index'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'preparations.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Preparations</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('preparations.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @if ($preparations->isEmpty())
                <div class="well text-center">No preparations found.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th class="text-right" width="200px">Action</th>
                    </thead>
                    <tbody>
                        @foreach($preparations as $preparation)
                            <tr>
                                <td>
                                    <a href="{!! route('preparations.edit', [$preparation->id]) !!}">{{ $preparation->name }}</a>
                                </td>
                                <td class="text-right">
                                    <form method="post" action="{!! route('preparations.destroy', [$preparation->id]) !!}">
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this preparation?')"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                    <a class="btn btn-default btn-xs pull-right raw-margin-right-16" href="{!! route('preparations.edit', [$preparation->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $preparations; !!}
        </div>
    </div>

@stop

resources/views/preparations/show.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop