routes/web.php
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {
    /*
    |--------------------------------------------------------------------------
    | CKEditor Images Upload
    |--------------------------------------------------------------------------
    */
    Route::post('/upload_image', function() {
        $CKEditor = Input::get('CKEditor');
        $funcNum = Input::get('CKEditorFuncNum');
        $message = $url = '';
        if (Input::hasFile('upload')) {
            $file = Input::file('upload');
            if ($file->isValid()) {
                $filename = $file->getClientOriginalName();
                $file->move(storage_path().'/images/', $filename);
                $url = public_path() .'/images/' . $filename;
            } else {
                $message = 'An error occured while uploading the file.';
            }
        } else {
            $message = 'No file uploaded.';
        }
        return '<script>window.parent.CKEDITOR.tools.callFunction('.$funcNum.', "'.$url.'", "'.$message.'")</script>';
    });


    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');



    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

    });
    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
        /*
        |--------------------------------------------------------------------------
        | Recipe Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('recipes', 'RecipesController', ['except' => ['show']]);
        Route::get('team/{slug}', 'RecipesController@showBySlug');
        Route::post('recipes/search', [
            'as' => 'recipes.search',
            'uses' => 'RecipesController@search'
            ]);

        /*
        |--------------------------------------------------------------------------
        | Device Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('devices', 'DevicesController', ['except' => ['show']]);
        Route::post('devices/search', [
            'as' => 'devices.search',
            'uses' => 'DevicesController@search'
            ]);



        
        /*
        |--------------------------------------------------------------------------
        | File Manager
        |--------------------------------------------------------------------------
        */ 

        Route::group(['prefix' => 'filemanager','middleware' => 'auth'], function() {    
            Route::get('admin', 'FilemanagerLaravelController@getAdmin');
            Route::get('show', 'FilemanagerLaravelController@getShow');
            Route::post('connectors', 'FilemanagerLaravelController@postConnectors');
        });



        /*
        |--------------------------------------------------------------------------
        | Preparation Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('preparations', 'PreparationsController', ['except' => ['show']]);
        Route::post('preparations/search', [
            'as' => 'preparations.search',
            'uses' => 'PreparationsController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Ingredient Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('ingredients', 'IngredientsController', ['except' => ['show']]);
        Route::post('ingredients/search', [
            'as' => 'ingredients.search',
            'uses' => 'IngredientsController@search'
        ]);


        /*
        |--------------------------------------------------------------------------
        | Category Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('categories', 'CategoriesController', ['except' => ['show']]);
        Route::post('categories/search', [
            'as' => 'categories.search',
            'uses' => 'CategoriesController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Step Routes
        |--------------------------------------------------------------------------
        */

        Route::resource('steps', 'StepsController', ['except' => ['show']]);
        Route::post('steps/search', [
            'as' => 'steps.search',
            'uses' => 'StepsController@search'
        ]);
        /*
        |-------------------------------------------------------------
        | Location Routes
        |-------------------------------------------------------------
        */

        Route::resource('locations', 'LocationsController', ['except' => ['show']]);
        Route::post('locations/search', [
            'as' => 'locations.search',
            'uses' => 'LocationsController@search'
        ]);

        
        
    });
});
Route::get('admin/filemanager/connectors', 'FilemanagerLaravelController@getConnectors');

Route::group(['middleware' => 'cacheable'], function () {
    /*
    |--------------------------------------------------------------------------
    | Welcome Page
    |--------------------------------------------------------------------------
    */

    Route::get('/', 'PagesController@home');

    
    

    /*
    |--------------------------------------------------------------------------
    | Image Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('images', 'ImagesController', ['except' => ['show']]);
    Route::post('images/search', [
        'as' => 'images.search',
        'uses' => 'ImagesController@search'
    ]);

app/Models/Device.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Device extends Model
{
    use SoftDeletes;
    public $table = "devices";

    public $primaryKey = "id";

    public $timestamps = true;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public $fillable = [
    'id',
    'user_id',
    'token',
    'name',
    'platforms',
    'deleted_at',
    'created_at',
    'updated_at',

    ];

    public static $rules = array(
        'token' => 'required|unique:devices',
        'name' => 'required',
        'platforms' => 'required',
    );


    /**
     * Get the user that owns the device.
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

}

app/Http/Controllers/Api/DevicesController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\DeviceService;
use App\Http\Requests\DeviceCreateRequest;
use App\Http\Requests\DeviceUpdateRequest;
use App\Models\Device;

class DevicesController extends Controller
{
    public function __construct(DeviceService $deviceService)
    {
        $this->service = $deviceService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $devices = $this->service->paginated();
        return response()->json($devices);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $devices = $this->service->search($request->search);
        return response()->json($devices);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\DeviceCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DeviceCreateRequest $request)
    {
        return response()->json(['foo' => 'bar']);

        $result = $this->service->create($request->except('_token'));
        
        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to create device'], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $device = $this->service->find($id);
        return response()->json($device);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\DeviceUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DeviceUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to update device'], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return response()->json(['success' => 'device was deleted'], 200);
        }

        return response()->json(['error' => 'Unable to delete device'], 500);
    }


    public function register(Request $request)
    {

        $data = $request->only('devicetoken', 'name', 'platforms', 'user_id');

        $result = $this->service->create($data);
        
        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to create device'], 500);
    }
}

app/Http/Controllers/DevicesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\DeviceService;
use App\Http\Requests\DeviceCreateRequest;
use App\Http\Requests\DeviceUpdateRequest;

class DevicesController extends Controller
{
    public function __construct(DeviceService $deviceService)
    {
        $this->service = $deviceService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $devices = $this->service->paginated();
        return view('devices.index')->with('devices', $devices);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $devices = $this->service->search($request->search);
        return view('devices.index')->with('devices', $devices);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('devices.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\DeviceCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DeviceCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('devices.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('devices.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the device.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $device = $this->service->find($id);
        return view('devices.show')->with('device', $device);
    }

    /**
     * Show the form for editing the device.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $device = $this->service->find($id);
        return view('devices.edit')->with('device', $device);
    }

    /**
     * Update the devices in storage.
     *
     * @param  \Illuminate\Http\DeviceUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DeviceUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the devices from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('devices.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('devices.index'))->with('message', 'Failed to delete');
    }
}

resources/views/devices/create.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Create'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'devices.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Devices: Create</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {!! Form::open(['route' => 'devices.store']) !!}

            @form_maker_table("devices")

            {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/devices/edit.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Edit'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'devices.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Devices: Edit</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('devices.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            {!! Form::model($device, ['route' => ['devices.update', $device->id], 'method' => 'patch']) !!}

            @form_maker_object($device, FormMaker::getTableColumns('devices'))

            {!! Form::submit('Update', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/devices/index.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Index'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'devices.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Devices</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('devices.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @if ($devices->isEmpty())
                <div class="well text-center">No devices found.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th class="text-right" width="200px">Action</th>
                    </thead>
                    <tbody>
                        @foreach($devices as $device)
                            <tr>
                                <td>
                                    <a href="{!! route('devices.edit', [$device->id]) !!}">{{ $device->name }}</a>
                                </td>
                                <td class="text-right">
                                    <form method="post" action="{!! route('devices.destroy', [$device->id]) !!}">
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this device?')"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                    <a class="btn btn-default btn-xs pull-right raw-margin-right-16" href="{!! route('devices.edit', [$device->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $devices; !!}
        </div>
    </div>

@stop

resources/views/devices/show.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop